main: com.bukkthat.paidhealplugin.PaidHealPlugin
version: 1.0.0
name: PaidHealPlugin
authors: [Tzeentchful, gomeow]
depend: [Vault]

commands:
  heal:
    description: Heals yourself or another player.
    usage: /<command> [player to heal]
